platform:
  - x64
environment:
  global:
    APPVEYOR_OS_NAME: windows
    GOPATH: c:\gopath
    BINTRAY_PATH: twstrike/coyim/coyim-bin/windows
    BINTRAY_USER:
      secure: HvXDg/3xn3Du2GPXPyf1tQ==
    BINTRAY_APIKEY:
      secure: pKFoGMJ1yEvd9hI9yF8a7D5fp5xGt53GdSrV3/g2CVbWiUfNoAXyYzHC1R4jSUqQ
  matrix:
    #- MSYS2_ARCH: x86_64
    #  MSYS2_BITS: 64
    #  MSYSTEM: MSYS2
    #  METHOD: ci
    #- MSYS2_ARCH: i686
    #  MSYS2_BITS: 32
    #  MSYSTEM: MINGW32
    #  METHOD: cross
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      METHOD: cross
      MSYS2_BASEVER: 20150916
install:
  - .\ci\install-deps-windows.bat
build_script:
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/twstrike/coyim && make deps-u"'
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/twstrike/coyim && make build-gui-win"'
after_build:
  - .\ci\build-windows-bundle.bat
artifacts:
  - path: coyim.zip
    name: CoyIM
deploy_script:
  - SET APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_BRANCH%
  - if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  - curl -T coyim.zip -u "%BINTRAY_USER%:%BINTRAY_APIKEY%" "https://api.bintray.com/content/twstrike/coyim/coyim-bin/%APPVEYOR_BUILD_VERSION%/%APPVEYOR_BUILD_VERSION%/windows/CoyIM.zip?override=1&publish=1"
